- name: Install agent on Windows hosts
  block:
      - name: Discover sensor version and path
        win_uri:
          url: "https://{{ server_ip }}/cloudlens/static/agent-update/windows/latest/"
          return_content: yes
          validate_certs: "{{ ssl_verify }}"

        register: latest_agent_response

      - name:
        set_fact:
          latest_agent_response_json_content: "{{ latest_agent_response.content|from_json }}"
      - name:
        set_fact:
          exe_agents_list: "{{ latest_agent_response_json_content | map (attribute='name') | list | select('match', '^.*exe') | list }}"

      - name: Install sensor if one is available
        block:
          - name: Get the sensor exe
            win_get_url: 
              url: "https://{{ server_ip }}/cloudlens/static/agent-update/windows/latest/{{ exe_agents_list[0] }}"
              dest: "{{ ansible_env.HOME }}\\sensor.exe"
              validate_certs: "{{ ssl_verify }}"

          - name: Run sensor
            win_command: '{{ ansible_env.HOME }}\\sensor.exe /install /quiet Server="{{ server_ip }}"  Project_Key="{{ project_key }}"  SSL_Verify="{{ ssl_verify }}" Auto_Update="{{ auto_update }}" -Wait'
        when: exe_agents_list[0] is defined

      - name: No sensor is available
        fail: msg="No windows sensor is available"
        when: exe_agents_list[0] is undefined
  when: '"Win32NT" in ansible_system'